Issue #13 - Criar README
app-masters/doar-computadores-frontend pull request #17
Opened 2022-08-13 14:17 UTC by abreuthrj

Adicionado o README com base no [Backend](https://github.com/app-masters/doar-computadores-backend).

Adicionado o `all-contributors-cli` ao projeto.
Adicionados os contribuidores retornados da [API do GitHub](https://api.github.com/repos/app-masters/doar-computadores-frontend/contributors).

Alguns outros arquivos foram modificados ao rodar o Prettier.

2022-08-15 12:54 UTC, jfbaraky requested changes

2022-08-15 12:54 UTC, jfbaraky commented on .all-contributorsrc
> +  "contributorsPerLine": 7
Ficou faltando o Douglas :D

2022-08-15 16:42 UTC, abreuthrj commented on .all-contributorsrc
> +  "contributorsPerLine": 7
Adicionado! 👍

2022-08-16 16:33 UTC, jfbaraky approved these changes

2022-08-16 16:34 UTC, jfbaraky requested changes
Na verdade, está com alguns conflitos

2022-08-17 17:31 UTC, jfbaraky approved these changes

2022-08-17 17:31 UTC, merged